### ISSUE TITLE
LogFilePath n'est pas pris en compte

### ISSUE THREAD

**Issue by GargamPierre** [LuccaSA/Lucca.Logs#43]
On s'attend à pouvoir mettre un chemin local dans la configuration pour LogFilePath et pouvoir y trouver nos logs.

**Comment by seguins** [comment]
Je viens de tester sur la dernière version, le bug n'est pas reproductible.

Je ferme l'issue. Si le problème persiste, ré-ouvre l'issue avec le détail de ta configuration + injection de `Lucca.Logs`.
